'use strict';

module.exports = {
    extends: ['plugin:you-dont-need-lodash-underscore/compatible'],
    plugins: ['unused-imports', 'unicorn'],
    rules: {
        'unused-imports/no-unused-imports': 'error',
        'unused-imports/no-unused-vars': 'warn',
        'unicorn/better-regex': 'warn',
        'unicorn/catch-error-name': 'warn',
        'unicorn/consistent-destructuring': 'warn',
        'unicorn/custom-error-definition': 'warn',
        'unicorn/error-message': 'error',
        'unicorn/escape-case': 'warn',
        'unicorn/new-for-builtins': 'warn',
        'unicorn/no-array-method-this-argument': 'warn',
        'unicorn/no-document-cookie': 'warn',
        'unicorn/no-empty-file': 'error',
        'unicorn/no-instanceof-array': 'warn',
        'unicorn/no-invalid-remove-event-listener': 'warn',
        'unicorn/no-nested-ternary': 'warn',
        'no-nested-ternary': 'off',
        'unicorn/no-new-array': 'warn',
        'unicorn/no-new-buffer': 'warn',
        'unicorn/no-null': 'warn',
        'unicorn/no-typeof-undefined': 'warn',
        'unicorn/no-useless-fallback-in-spread': 'warn',
        'unicorn/no-useless-length-check': 'warn',
        'unicorn/no-useless-promise-resolve-reject': 'error',
        'unicorn/no-useless-undefined': 'warn',
        'unicorn/no-zero-fractions': 'warn',
        'unicorn/number-literal-case': 'warn',
        'unicorn/numeric-separators-style': 'warn',
        'unicorn/prefer-add-event-listener': 'warn',
        'unicorn/prefer-array-find': 'warn',
        'unicorn/prefer-array-flat-map': 'warn',
        'unicorn/prefer-array-flat': 'off',
        'unicorn/prefer-array-index-of': 'warn',
        'unicorn/prefer-array-some': 'warn',
        'unicorn/prefer-at': 'warn',
        'unicorn/prefer-blob-reading-methods': 'warn',
        'unicorn/prefer-code-point': 'warn',
        'unicorn/prefer-date-now': 'warn',
        'unicorn/prefer-dom-node-append': 'warn',
        'unicorn/prefer-event-target': 'warn',
        'unicorn/prefer-export-from': 'warn',
        'unicorn/prefer-includes': 'warn',
        'unicorn/prefer-keyboard-event-key': 'warn',
        'unicorn/prefer-logical-operator-over-ternary': 'warn',
        'unicorn/prefer-modern-math-apis': 'warn',
        'unicorn/prefer-module': 'off',
        'unicorn/prefer-native-coercion-functions': 'warn',
        'unicorn/prefer-negative-index': 'warn',
        'unicorn/prefer-number-properties': 'warn',
        'unicorn/prefer-object-from-entries': 'warn',
        'unicorn/prefer-optional-catch-binding': 'warn',
        'unicorn/prefer-prototype-methods': 'error',
        'unicorn/prefer-query-selector': 'warn',
        'unicorn/prefer-reflect-apply': 'warn',
        'unicorn/prefer-regexp-test': 'warn',
        'unicorn/prefer-set-size': 'warn',
        'unicorn/prefer-spread': 'warn',
        'unicorn/prefer-string-replace-all': 'warn',
        'unicorn/prefer-string-slice': 'warn',
        'unicorn/prefer-string-starts-ends-with': 'warn',
        'unicorn/prefer-string-trim-start-end': 'warn',
        'unicorn/prefer-switch': ['warn', { minimumCases: 4 }],
        'unicorn/prefer-ternary': ['warn', 'only-single-line'],
        'unicorn/prefer-type-error': 'warn',
        'unicorn/relative-url-style': 'warn',
        'unicorn/text-encoding-identifier-case': 'warn',
        'unicorn/throw-new-error': 'warn'
    }
};